# startcode compose
version: "3.8"
services:
    billing:
        image: billing
        depends_on:
            - rabbitmq
    sales:
        image: sales
        depends_on:
            - rabbitmq
    shipping:
        image: shipping
        depends_on:
            - rabbitmq
    rabbitmq:
        image: "rabbitmq:3.12-management"
        ports:
            - "15672:15672"
            - "5672:5672"
        healthcheck:
            test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
            interval: 10s
            retries: 5
# endcode